<?php

/**
 * Implements hook_restws_resource_info().
 *
 * Adds a mapping layer between Publisher API and entity types.
 */
function pubapi_restws_resource_info() {
  $result = array();
  foreach (pubapi_get_structure() as $type => $info) {
    $result[$type] = array(
      'label' => $info['label'],
      'class' => 'PubApiResourceController',
      'properties' => $info['properties'],
    );
  }
  return $result;
}

/**
 * Gets the API to Entity property map.
 *
 * @return array
 *   An associative array of info explaining how Drupal entities map to our API.
 *   Containing:
 *   - entity: The mapped entity type
 *   - bundle: The mapped bundle name
 *   - id: The entity ID key
 *   - ADDITIONAL PROPERTY INFO REQUIRED BY OUR API SCHEMA.
 */
function pubapi_get_map() {
  $map = array();
  foreach (pubapi_get_structure() as $resource => $info) {
    $map[$resource]['entity'] = variable_get("pubapi_ui_entity_type_{$resource}");
    $map[$resource]['bundle'] = variable_get("pubapi_ui_bundle_{$resource}");
    foreach (array_keys($info['properties']) as $property_name) {
      $map[$resource][$property_name] = variable_get("pubapi_ui_{$resource}_property_{$property_name}");
    }
  }
  return $map;
}

/**
 * Gets POC API schema info.
 *
 * @return array
 *   An associative array, containing:
 *   - label: The REST resource object label.
 *   - properties: An array of property information suitable for the $info param
 *     of entity_metadata_wrapper()
 */
function pubapi_get_structure() {
  $structure = array();

  $structure['show'] = array(
    'label' => t('Show'),
    'properties' => array(
      'name' => array(
        'type' => 'text',
        'label' => t('Show name'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'id' => array(
        'type' => 'integer',
        'label' => t('Show ID'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'description' => array(
        'type' => 'text',
        'label' => t('Show description'),
        // @todo Consider refactoring to use entity_metadata_field_text_get().
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'genre' => array(
        'type' => 'text',
        'label' => t('Show genre'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'seasons' => array(
        'type' => 'integer',
        'label' => t("The show's seasons IDs"),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'status' => array(
        'type' => 'integer',
        'label' => t('Show published status'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
    ),
  );

  $structure['season'] = array(
    'label' => t('Season'),
    'properties' => array(
      'name' => array(
        'type' => 'text',
        'label' => t('Season name'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'id' => array(
        'type' => 'integer',
        'label' => t('Season ID'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'description' => array(
        'type' => 'text',
        'label' => t('Season description'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'show' => array(
        'type' => 'integer',
        'label' => t("The season's show ID"),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'episode' => array(
        'type' => 'integer',
        'label' => t("The season's episodes IDs"),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'status' => array(
        'type' => 'integer',
        'label' => t('Season published status'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
    ),
  );

  $structure['episode'] = array(
    'label' => t('Episode'),
    'properties' => array(
      'name' => array(
        'type' => 'text',
        'label' => t('Episode name'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'id' => array(
        'type' => 'integer',
        'label' => t('Episode ID'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'description' => array(
        'type' => 'text',
        'label' => t('Episode description'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'show' => array(
        'type' => 'integer',
        'label' => t("The episode's show ID"),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'season' => array(
        'type' => 'integer',
        'label' => t("The episode's season ID"),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'status' => array(
        'type' => 'integer',
        'label' => t('Episode published status'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
    ),
  );

  $structure['blog'] = array(
    'label' => t('Blog'),
    'properties' => array(
      'name' => array(
        'type' => 'text',
        'label' => t('Blog name'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'id' => array(
        'type' => 'integer',
        'label' => t('Blog ID'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'description' => array(
        'type' => 'text',
        'label' => t('Blog description'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'show' => array(
        'type' => 'integer',
        'label' => t("The blog's show ID"),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'season' => array(
        'type' => 'integer',
        'label' => t("The blog's season ID"),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'episode' => array(
        'type' => 'integer',
        'label' => t("The blog's episode ID"),
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'status' => array(
        'type' => 'integer',
        'label' => t('Blog published status'),
        'getter callback' => 'entity_property_verbatim_get',
      ),
    ),

    $structure['gallery'] = array(
      'label' => t('Gallery'),
      'properties' => array(
        'name' => array(
          'type' => 'text',
          'label' => t('Gallery name'),
          'getter callback' => 'entity_property_verbatim_get',
        ),
        'id' => array(
          'type' => 'integer',
          'label' => t('Gallery ID'),
          'getter callback' => 'entity_property_verbatim_get',
        ),
        'description' => array(
          'type' => 'text',
          'label' => t('Gallery description'),
          'getter callback' => 'entity_property_verbatim_get',
        ),
        'photos' => array(
          'type' => 'file',
          'label' => t("The gallery's photos"),
          // @todo Refactor to use entity_metadata_field_file_get().
          'getter callback' => 'entity_property_verbatim_get',
        ),
        'show' => array(
          'type' => 'integer',
          'label' => t("The gallery's show ID"),
          'getter callback' => 'entity_property_verbatim_get',
        ),
        'season' => array(
          'type' => 'integer',
          'label' => t("The gallery's season ID"),
          'getter callback' => 'entity_property_verbatim_get',
        ),
        'episode' => array(
          'type' => 'integer',
          'label' => t("The gallery's episode ID"),
          'getter callback' => 'entity_property_verbatim_get',
        ),
        'status' => array(
          'type' => 'integer',
          'label' => t('Gallery published status'),
          'getter callback' => 'entity_property_verbatim_get',
        ),
      ),
    ),
  );

  return $structure;
}
