<?php

/**
 * Implements hook_restws_resource_info().
 *
 * Adds a mapping layer between Publisher API and entity types.
 */
function pubapi_restws_resource_info() {
  $result = array();
  foreach (pubapi_get_structure() as $type => $info) {
    $result[$type] = array(
      'label' => $info['label'],
      'class' => 'PubApiResourceController',
    );
  }
  return $result;
}

/**
 * Gets the API to Entity property map.
 *
 * @todo Get the 'id' key from entity_get_info().
 * @todo Replace the 'pubapi_map' variable with the forthcoming mapping UI.
 *
 * @return array
 *   An associative array of info explaining how Drupal entities map to our API.
 *   Containing:
 *   - entity: The mapped entity type
 *   - bundle: The mapped bundle name
 *   - id: The entity ID key
 *   - ADDITIONAL PROPERTY INFO REQUIRED BY OUR API SCHEMA.
 */
function pubapi_get_map() {
  return variable_get('pubapi_map', array());
}

/**
 * Gets a POC API schema info.
 *
 * @return array
 *   An associative array, containing:
 *   - label: The REST resource object label.
 *   - properties: An array of property information suitable for the $info param
 *     of entity_metadata_wrapper()
 */
function pubapi_get_structure() {
  $structure = array();

  $structure['show'] = array(
    'label' => t('Show'),
    'properties' => array(
      'name' => array(
        'type' => 'text',
        'label' => t('Show name'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'id' => array(
        'type' => 'integer',
        'label' => t('Show ID'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'description' => array(
        'type' => 'text',
        'label' => t('Show description'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'genre' => array(
        'type' => 'text',
        'label' => t('Show genre'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'status' => array(
        'type' => 'integer',
        'label' => t('Show published status'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
    ),
  );

  $structure['season'] = array(
    'label' => t('Season'),
    'properties' => array(
      'name' => array(
        'type' => 'text',
        'label' => t('Season name'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'id' => array(
        'type' => 'integer',
        'label' => t('Season ID'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'description' => array(
        'type' => 'text',
        'label' => t('Season description'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'show' => array(
        'type' => 'integer',
        'label' => t("The season's show ID"),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'status' => array(
        'type' => 'integer',
        'label' => t('Season published status'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
    ),
  );

  $structure['episode'] = array(
    'label' => t('Episode'),
    'properties' => array(
      'name' => array(
        'type' => 'text',
        'label' => t('Episode name'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'id' => array(
        'type' => 'integer',
        'label' => t('Episode ID'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'description' => array(
        'type' => 'text',
        'label' => t('Episode description'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'show' => array(
        'type' => 'integer',
        'label' => t("The episode's show ID"),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'season' => array(
        'type' => 'integer',
        'label' => t("The episode's season ID"),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'status' => array(
        'type' => 'integer',
        'label' => t('Episode published status'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
    ),
  );

  $structure['blog'] = array(
    'label' => t('Blog'),
    'properties' => array(
      'name' => array(
        'type' => 'text',
        'label' => t('Blog name'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'id' => array(
        'type' => 'integer',
        'label' => t('Blog ID'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'description' => array(
        'type' => 'text',
        'label' => t('Blog description'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'show' => array(
        'type' => 'integer',
        'label' => t("The blog's show ID"),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'season' => array(
        'type' => 'integer',
        'label' => t("The blog's season ID"),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'episode' => array(
        'type' => 'integer',
        'label' => t("The blog's episode ID"),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
      'status' => array(
        'type' => 'integer',
        'label' => t('Blog published status'),
        'setter callback' => 'entity_property_verbatim_set',
        'getter callback' => 'entity_property_verbatim_get',
      ),
    ),
  );

  return $structure;
}
