<?php

/**
 * @file
 * Publisher API UI module.
 */

/**
 * Implements hook_menu().
 */
function pubapi_ui_menu() {
  $items = array();

  $items['admin/config/services/pubapi'] = array(
    'title' => 'Publisher API mapping',
    'description' => 'Map Publisher API to entity types and fields.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pubapi_ui_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'pubapi_ui.admin.inc',
  );

  return $items;
}
